namespace StreamingService.Persistence
{
    public static class MoviesData
    {
        public static readonly Dictionary<string, string> Movies = new Dictionary<string, string>
        {
            {"Joker","Sensitive"},
            {"Once Upon a Time in Hollywood","Sensitive"},
            {"The Lion King","Animation"},
            {"Shrek","Animation"},
            {"A Clockwork Orange","Sensitive"},
            {"Natural Born Killers","Sensitive"},
            {"Pulp Fiction","Sensitive"},
            {"Annabelle","Very Sensitive"},
            {"Kill Bill: Vol. 1","Sensitive"},
            {"Kill Bill: Vol. 2","Sensitive"},
            {"American Psycho","Sensitive"},
            {"Hostel","Sensitive"},
            {"Saw","Very Sensitive"},
            {"The Passion of the Christ","Sensitive"},
            {"Rambo","Sensitive"},
            {"Die Hard","Sensitive"},
            {"Gladiator","Sensitive"},
            {"300","Sensitive"},
            {"The Braveheart","Sensitive"},
            {"The Dark Knight","Sensitive"},
            {"Sin City","Sensitive"},
            {"Reservoir Dogs","Sensitive"},
            {"RoboCop","Sensitive"},
            {"The Texas Chain Saw Massacre","Sensitive"},
            {"The Silence of the Lambs","Sensitive"},
            {"Finding Nemo", "Animation"},
            {"Toy Story", "Animation"},
            {"Moana", "Animation"},
            {"Frozen", "Animation"},
            {"Zootopia", "Animation"},
            {"Coco", "Animation"},
            {"Tangled", "Animation"},
            {"Despicable Me", "Animation"},
            {"Kung Fu Panda", "Animation"},
            {"Cars", "Animation"},
            {"Ratatouille", "Animation"},
            {"Brave", "Animation"},
            {"Wreck-It Ralph", "Animation"},
            {"How to Train Your Dragon", "Animation"},
            {"Sing", "Animation"},
            {"Paddington", "Animation"},
            {"The Incredibles", "Animation"},
            {"Monsters, Inc.", "Animation"},
            {"he Paddington 2","Family"},
            {"The Jungle Book","Family"},
            {"Mary Poppins Returns","Family"},
            {"XXX","VerySensitive"}
        };
    }
}
